# Generated by Django 4.1.7 on 2023-03-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('small_description', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('status', models.BooleanField(default=0, help_text='0-show, 1-hidden')),
                ('image', models.ImageField(upload_to='prod_images')),
            ],
        ),
    ]
